version: '3.4'

services:
  todoapp.webapi:
    image: ${DOCKER_REGISTRY-}todoappwebapi
    build:
      context: .
      dockerfile: src\ToDoApp.WebApi\Dockerfile
    ports:
    - "5000:80"
    depends_on: 
    - redis
  redis:
    image: redis
    ports: 
    - 6379:6379
  mysql_db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ToDo
    ports:
      - "3307:3307"
    volumes:
      - mysql_db:/var/lib/mysql
volumes:
  mysql_db:
    driver: local
      